// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJSUwz-G-grVRbsiCDlGLbRpr05987GJg',
    appId: '1:350559133624:web:d6190683a9c29d77ecf94d',
    messagingSenderId: '350559133624',
    projectId: 'tinder-with-chuck-jokes',
    authDomain: 'tinder-with-chuck-jokes.firebaseapp.com',
    databaseURL: 'https://tinder-with-chuck-jokes-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tinder-with-chuck-jokes.appspot.com',
    measurementId: 'G-Y8BS92WY1B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvSqsdBxB0LKkJaTSWJKFVQtX_fpVUq0c',
    appId: '1:350559133624:android:1c42ec332da10d56ecf94d',
    messagingSenderId: '350559133624',
    projectId: 'tinder-with-chuck-jokes',
    databaseURL: 'https://tinder-with-chuck-jokes-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tinder-with-chuck-jokes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuyGLoy8XWlIyGxJ7eV_GINyqWDdhXp8E',
    appId: '1:350559133624:ios:866045d086e55829ecf94d',
    messagingSenderId: '350559133624',
    projectId: 'tinder-with-chuck-jokes',
    databaseURL: 'https://tinder-with-chuck-jokes-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tinder-with-chuck-jokes.appspot.com',
    iosClientId: '350559133624-htoard3tma2squ487q1heh6kc78vjhje.apps.googleusercontent.com',
    iosBundleId: 'com.example.tinderWithChuck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuyGLoy8XWlIyGxJ7eV_GINyqWDdhXp8E',
    appId: '1:350559133624:ios:866045d086e55829ecf94d',
    messagingSenderId: '350559133624',
    projectId: 'tinder-with-chuck-jokes',
    databaseURL: 'https://tinder-with-chuck-jokes-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tinder-with-chuck-jokes.appspot.com',
    iosClientId: '350559133624-htoard3tma2squ487q1heh6kc78vjhje.apps.googleusercontent.com',
    iosBundleId: 'com.example.tinderWithChuck',
  );
}
